Feature include git
redhat-actions/s2i-build pull request #40
Opened 2022-02-03 00:07 UTC by eformat

### Description
Quite often developers use the local git info during the build e.g. in Java land we use the git-commit-id-maven-plugin.

During s2i build we need to pass two flags to include the .git directory.

This change adds the '--copy' and ''--exclude=""' parameters to the s2i-build action. s2i by default will attempt to "git clone" your repo, even if it's a local repo. The relevant discussions and changes for s2i here were discussed here:

-- s2i build --copy (not exposed by action, so it always clones head)
https://github.com/openshift/source-to-image/issues/674#issuecomment-270557199
-- s2i build tar excludes .git when copying to build container
https://github.com/openshift/source-to-image/pull/460

### Related Issue(s)
N/A

### Checklist

- [X] This PR includes a documentation change
- [ ] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [ ] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [X] This change is a patch change
- [ ] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made
- added optional argument `include_git` which can be 'false' (anything else is considered 'true')

```yaml
      # Setup S2i and Build container image from source
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@main
        with:
          path_context: '.'
          # Builder image for a java project
          builder_image: 'registry.access.redhat.com/ubi8/openjdk-17:latest'
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          log_level: 5
          include_git: true
```

I'm not sure how the dist/ works for these actions repo's, i ran

```bash
npm run clean && npm run compile && npm run bundle
```
and tested the changes. Please let me know if i need to change anything in the PR to suit how you test & deploy them.

2022-02-04 05:54 UTC, divyansh42 commented
@eformat Thanks for the PR.
You have to do
`npm run lint` --> as CI checks include ESLint too.
`npx action-io-generator --actionYml ./action.yml --outFile ./src/generated/inputs-outputs.ts` --> to generate inputs and ouptuts file using action.yml. Also make sure you do not edit `./src/generated/inputs-outputs.ts` manually.
`npm run bundle` to update `dist/`

2022-02-04 05:57 UTC, divyansh42 requested changes
Few nits that you may want to address.

2022-02-04 05:57 UTC, divyansh42 commented on src/s2iExec.ts
> +    const includeGit = core.getInput(Inputs.INCLUDE_GIT, { required: false });
```suggestion
    const includeGit = core.getInput(Inputs.INCLUDE_GIT, { required: false }) | "false";
```

2022-02-04 05:57 UTC, divyansh42 commented on src/s2iExec.ts
> +    if (includeGit && includeGit != 'false') {
```suggestion
    if (includeGit === "true") {
```

2022-02-04 05:57 UTC, divyansh42 commented on src/generated/inputs-outputs.ts
> -     * The tags of the image to build. For multiple tags, seperate by a space. For example, "latest v1".
Please do not edit this manually.

2022-02-05 02:06 UTC, eformat commented
> Few nits that you may want to address.

nice one thanks @divyansh42  .. done.

2022-02-05 06:00 UTC, divyansh42 requested changes

2022-02-05 06:00 UTC, divyansh42 commented on src/s2iExec.ts
> +    const includeGit = core.getInput(Inputs.INCLUDE_GIT, { required: false });
It is not resolved yet. Could you please check once?

2022-02-05 06:01 UTC, divyansh42 commented
Also, can you add the link to the workflow where you have tested these changes?

2022-02-06 02:23 UTC, eformat commented
ah soz, fixed initialization.
i have been testing in this workflow here

https://github.com/eformat/pet-battle-api/blob/master/.github/workflows/build_container.yaml#L40

2022-02-07 06:56 UTC, divyansh42 approved these changes
Thanks!

2022-02-09 03:26 UTC, merged

2022-02-09 03:36 UTC, divyansh42 commented
I've created a release for this feature. You can use this in `v2/v2.2`